# Generated by Django 5.2.10 on 2026-01-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='publicacoes/', verbose_name='logo')),
                ('descricao', models.TextField(verbose_name='descrição pública')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='publicado em')),
                ('destaque', models.BooleanField(default=False, help_text='Exibir em destaque na página inicial.', verbose_name='destaque')),
                ('ativo', models.BooleanField(default=True, help_text='Se desmarcado, não aparece na vitrine.', verbose_name='ativo')),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicacao', to='projetos.projeto', verbose_name='projeto')),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-publicado_em'],
                'indexes': [models.Index(fields=['ativo', 'destaque'], name='publicacoes_ativo_29bf39_idx'), models.Index(fields=['publicado_em'], name='publicacoes_publica_75ea09_idx')],
            },
        ),
    ]
