# Generated by Django 5.2.10 on 2026-01-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deletado em')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('inicio', models.DateTimeField(db_index=True, verbose_name='data de início')),
                ('fim', models.DateTimeField(verbose_name='data de encerramento')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ENCERRADO', 'Encerrado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='status')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editais_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'edital',
                'verbose_name_plural': 'editais',
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['status', 'inicio'], name='editais_edi_status_38da6b_idx'), models.Index(fields=['criado_por'], name='editais_edi_criado__22df71_idx')],
            },
        ),
    ]
