# Generated by Django 5.2.10 on 2026-01-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoMentoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=80, verbose_name='área de mentoria')),
                ('justificativa', models.TextField(verbose_name='justificativa')),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('NEGADA', 'Negada')], db_index=True, default='SOLICITADA', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorias', to=settings.AUTH_USER_MODEL, verbose_name='mentor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_mentoria', to='projetos.projeto', verbose_name='projeto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_mentoria', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'solicitação de mentoria',
                'verbose_name_plural': 'solicitações de mentoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['projeto'], name='mentorias_s_projeto_d6ed37_idx'), models.Index(fields=['solicitante'], name='mentorias_s_solicit_136702_idx'), models.Index(fields=['status'], name='mentorias_s_status_3c50f5_idx'), models.Index(fields=['mentor'], name='mentorias_s_mentor__9c0215_idx')],
            },
        ),
    ]
