# Generated by Django 5.2.10 on 2026-01-24 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(db_index=True, max_length=80, verbose_name='ação')),
                ('entidade', models.CharField(db_index=True, max_length=80, verbose_name='entidade')),
                ('entidade_id', models.BigIntegerField(verbose_name='ID da entidade')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='dados anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='dados novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entidade', 'entidade_id'], name='core_logaud_entidad_880a7c_idx'), models.Index(fields=['usuario', 'created_at'], name='core_logaud_usuario_caec05_idx')],
            },
        ),
    ]
