# Generated by Django 5.2.10 on 2026-01-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deletado em')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('area', models.CharField(max_length=80, verbose_name='área')),
                ('status', models.CharField(choices=[('PRE_SUBMISSAO', 'Pré-submissão'), ('SUBMETIDO', 'Submetido'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('AJUSTES', 'Ajustes'), ('INCUBADO', 'Incubado'), ('INATIVO', 'Inativo'), ('DESLIGADO', 'Desligado')], db_index=True, default='PRE_SUBMISSAO', max_length=20, verbose_name='status')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('funcao', models.CharField(max_length=80, verbose_name='função na equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'membro da equipe',
                'verbose_name_plural': 'membros da equipe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral')], max_length=20, verbose_name='período')),
                ('conteudo', models.TextField(verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_criados', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'relatório de progresso',
                'verbose_name_plural': 'relatórios de progresso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENVIADA', 'Enviada'), ('EM_AVALIACAO', 'Em avaliação'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('AJUSTES_SOLICITADOS', 'Ajustes solicitados')], db_index=True, default='ENVIADA', max_length=25, verbose_name='status')),
                ('submetido_em', models.DateTimeField(auto_now_add=True, verbose_name='submetido em')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissoes', to='editais.edital', verbose_name='edital')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissoes', to='projetos.projeto', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'submissão',
                'verbose_name_plural': 'submissões',
                'ordering': ['-submetido_em'],
            },
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['responsavel', 'status'], name='projetos_pr_respons_a9638b_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['status'], name='projetos_pr_status_7fdf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='membroequipe',
            index=models.Index(fields=['projeto'], name='projetos_me_projeto_d2e56b_idx'),
        ),
        migrations.AddIndex(
            model_name='relatorioprogresso',
            index=models.Index(fields=['projeto', 'created_at'], name='projetos_re_projeto_f7bc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['projeto', 'edital'], name='projetos_su_projeto_3625d0_idx'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['status'], name='projetos_su_status_bce5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['edital', 'status'], name='projetos_su_edital__5a2592_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissao',
            constraint=models.UniqueConstraint(fields=('projeto', 'edital'), name='unique_projeto_edital'),
        ),
    ]
