# Generated by Django 5.2.10 on 2026-01-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('NECESSITA_AJUSTES', 'Necessita ajustes')], db_index=True, max_length=20, verbose_name='resultado')),
                ('comentarios', models.TextField(verbose_name='comentários')),
                ('avaliado_em', models.DateTimeField(auto_now_add=True, verbose_name='avaliado em')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='avaliador')),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='projetos.submissao', verbose_name='submissão')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-avaliado_em'],
                'indexes': [models.Index(fields=['submissao', 'avaliado_em'], name='avaliacoes__submiss_b726b5_idx'), models.Index(fields=['avaliador'], name='avaliacoes__avaliad_b4d755_idx'), models.Index(fields=['resultado'], name='avaliacoes__resulta_0741d0_idx')],
            },
        ),
    ]
